export type ProductColor = {
  name: string;
  hex: string;
};

export type ProductData = {
  id: string;
  name: string;
  subtitle: string;
  price: number;
  images: string[];
  colors: ProductColor[];
  description: string;
  details: string[];
  paymentOptions: string[];
  shipping: string[];
  relatedProducts: RelatedProduct[];
  createdAt?: string;
};

export type RelatedProduct = {
  id: string;
  name: string;
  price: number;
  image: string;
};

export const PRODUCTS: Record<string, ProductData> = {
  "d1": {
    id: "d1",
    name: "Nexel Aura Pro",
    subtitle: "Professional Hair Care",
    price: 399,
    images: [
      "/prd_pics/minimalistic/Screenshot 2026-05-05 at 18.43.57.png",
      "/prd_pics/minimalistic/Screenshot 2026-05-05 at 18.44.00.png",
      "/prd_pics/minimalistic/Screenshot 2026-05-05 at 18.44.15.png",
    ],
    colors: [{ name: "Matte Grey", hex: "#333333" }, { name: "Copper", hex: "#b87333" }],
    description: "The Nexel Aura Pro redefines hair drying. With high-speed ionic technology and intelligent heat control, it delivers professional results while protecting your hair's natural shine.",
    details: ["High-speed digital motor (110,000 rpm)", "Intelligent heat control", "Ionic technology reduces static", "Lightweight magnesium body"],
    paymentOptions: ["Pay in full", "0% APR Installments"],
    shipping: ["Free standard shipping", "30-day returns"],
    relatedProducts: [
      {
        id: "d4",
        name: "Nexel Travel Go",
        price: 199,
        image: "/prd_pics/dyson dryer/Screenshot 2026-05-05 at 16.36.15.png",
      },
    ],
  },
  "d4": {
    id: "d4",
    name: "Nexel Travel Go",
    subtitle: "Compact Performance",
    price: 199,
    images: ["/prd_pics/dyson dryer/Screenshot 2026-05-05 at 16.36.15.png"],
    colors: [{ name: "Arctic White", hex: "#ffffff" }],
    description: "Your perfect travel companion. Foldable design with full-sized power to keep your hair looking great anywhere in the world.",
    details: ["Foldable handle", "Dual voltage support", "Ultra-lightweight"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "d1",
        name: "Nexel Aura Pro",
        price: 399,
        image: "/prd_pics/dyson dryer/Gemini_Generated_Image_rr5o1hrr5o1hrr5o.png",
      },
    ],
  },
  "d2": {
    id: "d2",
    name: "Nexel Ionic Dry",
    subtitle: "High Speed Drying",
    price: 299,
    images: [
      "/prd_pics/lifestye_dyson/Screenshot 2026-05-05 at 18.44.58.png",
      "/prd_pics/lifestye_dyson/Screenshot 2026-05-05 at 18.45.52.png",
      "/prd_pics/lifestye_dyson/Screenshot 2026-05-05 at 18.46.00.png",
      "/prd_pics/lifestye_dyson/Screenshot 2026-05-05 at 18.46.15.png",
    ],
    colors: [{ name: "Space Grey", hex: "#555555" }],
    description: "Powerful and portable. The Ionic Dry uses advanced airflow technology to dry hair 50% faster than traditional models.",
    details: ["High-speed motor", "Ionic care"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "d1",
        name: "Nexel Aura Pro",
        price: 399,
        image: "/prd_pics/dyson dryer/Gemini_Generated_Image_rr5o1hrr5o1hrr5o.png",
      },
    ],
  },
  "d3": {
    id: "d3",
    name: "Nexel Nano Care",
    subtitle: "Hair Hydration",
    price: 249,
    images: ["/prd_pics/dyson dryer/Screenshot 2026-05-05 at 16.37.18.png"],
    colors: [{ name: "Satin Blue", hex: "#000080" }],
    description: "Hydrates as it dries. Nanoe technology infuses moisture into your hair, leaving it smooth and shiny.",
    details: ["Nanoe technology", "Quick-dry nozzle"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "d1",
        name: "Nexel Aura Pro",
        price: 399,
        image: "/prd_pics/dyson dryer/Gemini_Generated_Image_rr5o1hrr5o1hrr5o.png",
      },
    ],
  },
  "s1": {
    id: "s1",
    name: "Nexel Air Wrap",
    subtitle: "Multi-Styler",
    price: 549,
    images: ["/prd_pics/dyson dryer/Screenshot 2026-05-04 at 18.54.22.png"],
    colors: [{ name: "Prussian Blue", hex: "#003153" }],
    description: "Curl, wave, smooth, and dry with no extreme heat. The Air Wrap uses the Coanda effect to style hair safely.",
    details: ["Coanda effect", "Intelligent heat control"],
    paymentOptions: ["Installments available"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "d1",
        name: "Nexel Aura Pro",
        price: 399,
        image: "/prd_pics/dyson dryer/Gemini_Generated_Image_rr5o1hrr5o1hrr5o.png",
      },
    ],
  },
  "s2": {
    id: "s2",
    name: "Nexel Multi Styler",
    subtitle: "Styling Perfection",
    price: 499,
    images: ["/prd_pics/dyson dryer/Screenshot 2026-05-04 at 18.55.32.png"],
    colors: [{ name: "Satin Finish", hex: "#dcdcdc" }],
    description: "One tool for every look. Interchangeable heads allow you to go from straight to curly in minutes.",
    details: ["6 styling attachments", "3 temperature settings"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "s1",
        name: "Nexel Air Wrap",
        price: 549,
        image: "/prd_pics/dyson dryer/Screenshot 2026-05-04 at 18.54.22.png",
      },
    ],
  },
  "i1": {
    id: "i1",
    name: "Nexel Volta V7",
    subtitle: "Precision Steaming",
    price: 189,
    images: ["/prd_pics/steamone/Screenshot 2026-05-01 at 18.06.20.png"],
    colors: [{ name: "Chrome Silver", hex: "#c0c0c0" }],
    description: "Precision meets power. Dual-heating technology ensures a consistent, high-pressure steam for any fabric.",
    details: ["2800W power", "Ceramic-coated soleplate"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "i2",
        name: "Nexel Pro Steam",
        price: 129,
        image: "/prd_pics/steamone/Screenshot 2026-05-05 at 16.52.07.png",
      },
    ],
  },
  "i2": {
    id: "i2",
    name: "Nexel Pro Steam",
    subtitle: "Classic Ironing",
    price: 129,
    images: ["/prd_pics/steamone/Screenshot 2026-05-05 at 16.52.07.png"],
    colors: [{ name: "Titanium", hex: "#878787" }],
    description: "Reliable steam ironing with a heavy-duty soleplate for persistent creases.",
    details: ["Steam boost", "Vertical steaming"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "i1",
        name: "Nexel Volta V7",
        price: 189,
        image: "/prd_pics/steamone/Screenshot 2026-05-01 at 18.06.20.png",
      },
    ],
  },
  "c1": {
    id: "c1",
    name: "Nexel Brew Master",
    subtitle: "The Art of Coffee",
    price: 849,
    images: ["/prd_pics/coffee machine/Screenshot 2026-05-01 at 18.03.40.png"],
    colors: [{ name: "Onyx Black", hex: "#1a1a1a" }],
    description: "The ultimate barista experience at home. Integrated conical burr grinder for the freshest espresso.",
    details: ["Built-in grinder", "PID temperature control"],
    paymentOptions: ["Installments available"],
    shipping: ["Free standard shipping"],
    relatedProducts: [
      {
        id: "c2",
        name: "Nexel Barista Pro",
        price: 1299,
        image: "/prd_pics/coffee machine/Screenshot 2026-05-01 at 18.04.05.png",
      },
    ],
  },
  "c2": {
    id: "c2",
    name: "Nexel Barista Pro",
    subtitle: "Advanced Espresso",
    price: 1299,
    images: ["/prd_pics/coffee machine/Screenshot 2026-05-01 at 18.04.05.png"],
    colors: [{ name: "Black Steel", hex: "#222222" }],
    description: "Professional grade extraction. Dual boilers allow for simultaneous brewing and milk steaming.",
    details: ["Dual boilers", "Pressure gauge"],
    paymentOptions: ["Installments available"],
    shipping: ["White glove delivery"],
    relatedProducts: [
      {
        id: "c1",
        name: "Nexel Brew Master",
        price: 849,
        image: "/prd_pics/coffee machine/Screenshot 2026-05-01 at 18.03.40.png",
      },
    ],
  },
  "c3": {
    id: "c3",
    name: "Nexel Rose Brew",
    subtitle: "Limited Edition",
    price: 249,
    images: ["/prd_pics/smeg/Screenshot 2026-05-05 at 16.56.04.png"],
    colors: [{ name: "Rose Pink", hex: "#ffb6c1" }],
    description: "Add a splash of color to your kitchen. Compact, powerful, and incredibly stylish.",
    details: ["Compact design", "One-touch brewing"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "c1",
        name: "Nexel Brew Master",
        price: 849,
        image: "/prd_pics/coffee machine/Screenshot 2026-05-01 at 18.03.40.png",
      },
    ],
  },
  "v1": {
    id: "v1",
    name: "Nexel Vacuum X20",
    subtitle: "Automated Perfection",
    price: 699,
    images: ["/prd_pics/vacum cleaner/Screenshot 2026-05-05 at 16.37.06.png"],
    colors: [{ name: "White", hex: "#ffffff" }],
    description: "Total home cleaning automation. LIDAR mapping and AI object recognition ensure no spot is missed.",
    details: ["LIDAR navigation", "6000Pa suction"],
    paymentOptions: ["Installments available"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "v2",
        name: "Nexel Robot Pro",
        price: 499,
        image: "/prd_pics/vacum cleaner/Screenshot 2026-05-05 at 16.37.51.png",
      },
    ],
  },
  "a1": {
    id: "a1",
    name: "Nexel Air Purifier",
    subtitle: "Clean Breathing",
    price: 299,
    images: ["/prd_pics/air-quality/air.jpg"],
    colors: [{ name: "White", hex: "#ffffff" }],
    description: "HEPA filtration for your home. Removes 99.9% of airborne particles, including allergens and smoke.",
    details: ["True HEPA filter", "Real-time air quality monitoring"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "a2",
        name: "Nexel Pure Flow",
        price: 199,
        image: "/prd_pics/air-quality/crember.jpg",
      },
    ],
  },
  "l1": {
    id: "l1",
    name: "Nexel Urban Scooter",
    subtitle: "Smart Mobility",
    price: 799,
    images: ["/prd_pics/lifestyle/ph.jpg"],
    colors: [{ name: "Obsidian", hex: "#111111" }],
    description: "Fast, foldable, and smart. The perfect solution for urban commuting with a 45km range.",
    details: ["45km range", "Smart app integration"],
    paymentOptions: ["Installments available"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "l2",
        name: "Nexel Smart Bike",
        price: 1499,
        image: "/prd_pics/lifestyle/ph1.jpg",
      },
    ],
  },
  "w2": {
    id: "w2",
    name: "Nexel Buds Pro",
    subtitle: "Personal Sound",
    price: 149,
    images: ["/prd_pics/lifestyle/son.jpg"],
    colors: [{ name: "Black", hex: "#000000" }],
    description: "High-fidelity sound with active noise cancellation. 8 hours of battery life on a single charge.",
    details: ["Active Noise Cancellation", "IPX4 water resistance"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [
      {
        id: "w3",
        name: "Nexel Sound X",
        price: 229,
        image: "/prd_pics/lifestyle/sony.jpg",
      },
    ],
  },

  // Added to ensure every nav/home item has a single product page.
  "s3": {
    id: "s3",
    name: "Nexel Pro Curler",
    subtitle: "Effortless Waves",
    price: 279,
    images: ["/prd_pics/dyson dryer/Screenshot 2026-05-05 at 16.40.00.png"],
    colors: [{ name: "Graphite", hex: "#2b2b2b" }],
    description: "Create soft curls and defined waves with consistent heat and a lightweight design.",
    details: ["Fast heat-up", "Auto shut-off", "Cool-touch tip"],
    paymentOptions: ["Pay in full", "Installments available"],
    shipping: ["Free shipping", "30-day returns"],
    relatedProducts: [],
  },
  "i3": {
    id: "i3",
    name: "Nexel Smart Station",
    subtitle: "Steam Base System",
    price: 229,
    images: ["/prd_pics/steamone/Screenshot 2026-05-05 at 16.53.45.png"],
    colors: [{ name: "White", hex: "#ffffff" }],
    description: "A compact steam station designed for fast crease removal with consistent output.",
    details: ["High-pressure steam", "Large water tank", "Quick refill"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "gs1": {
    id: "gs1",
    name: "Nexel Handheld Steamer",
    subtitle: "On-the-Go Refresh",
    price: 99,
    images: ["/prd_pics/steamone/Screenshot 2026-05-05 at 16.53.14.png"],
    colors: [{ name: "Charcoal", hex: "#3a3a3a" }],
    description: "Refresh garments quickly with a lightweight handheld steamer.",
    details: ["Ready in seconds", "Compact design", "Easy storage"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "gs2": {
    id: "gs2",
    name: "Nexel Vertical Pro",
    subtitle: "Vertical Steam Care",
    price: 179,
    images: ["/prd_pics/steamone/Screenshot 2026-05-05 at 16.52.56.png"],
    colors: [{ name: "Black", hex: "#000000" }],
    description: "Vertical steaming performance for everyday care and quick touch-ups.",
    details: ["Continuous steam", "Adjustable pole", "Fabric-safe"],
    paymentOptions: ["Pay in full", "Installments available"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "c4": {
    id: "c4",
    name: "Nexel Drip Master",
    subtitle: "Smart Brewing",
    price: 179,
    images: ["/prd_pics/smeg/Screenshot 2026-05-01 at 18.20.11.png"],
    colors: [{ name: "Cream", hex: "#f3efe6" }],
    description: "Clean, consistent drip coffee with a modern, minimal countertop footprint.",
    details: ["Programmable brew", "Keep-warm mode", "Easy clean"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "c5": {
    id: "c5",
    name: "Nexel Smart Grinder",
    subtitle: "Precision Grinding",
    price: 149,
    images: ["/prd_pics/smeg/Screenshot 2026-05-05 at 16.57.06.png"],
    colors: [{ name: "Black", hex: "#1f1f1f" }],
    description: "Dial-in your grind with consistent particle size for better extraction.",
    details: ["Multiple grind settings", "Low retention", "Easy dose control"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "v2": {
    id: "v2",
    name: "Nexel Robot Pro",
    subtitle: "Smart Robot Cleaning",
    price: 499,
    images: ["/prd_pics/vacum cleaner/Screenshot 2026-05-05 at 16.37.51.png"],
    colors: [{ name: "White", hex: "#ffffff" }],
    description: "Automated cleaning with smart navigation for everyday maintenance.",
    details: ["Smart mapping", "Auto recharge", "Multi-surface support"],
    paymentOptions: ["Installments available"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "v3": {
    id: "v3",
    name: "Nexel Handheld X",
    subtitle: "Compact Pickup",
    price: 129,
    images: ["/prd_pics/vacum cleaner/Screenshot 2026-05-05 at 16.42.46.png"],
    colors: [{ name: "Graphite", hex: "#2b2b2b" }],
    description: "Quick clean-ups made easy with a compact handheld vacuum.",
    details: ["Lightweight", "Crevice tool included", "Washable filter"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "a2": {
    id: "a2",
    name: "Nexel Pure Flow",
    subtitle: "Compact Filtration",
    price: 199,
    images: ["/prd_pics/air-quality/crember.jpg"],
    colors: [{ name: "White", hex: "#ffffff" }],
    description: "Compact air purification designed for bedrooms and small rooms.",
    details: ["HEPA filtration", "Quiet mode", "Filter life indicator"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "a3": {
    id: "a3",
    name: "Nexel Humidifier Pro",
    subtitle: "Comfort Air",
    price: 169,
    images: ["/prd_pics/air-quality/sdf.jpg"],
    colors: [{ name: "White", hex: "#ffffff" }],
    description: "Maintain comfortable humidity with a clean, modern design.",
    details: ["Adjustable output", "Easy refill", "Auto shut-off"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "l2": {
    id: "l2",
    name: "Nexel Smart Bike",
    subtitle: "Connected Commuting",
    price: 1499,
    images: ["/prd_pics/lifestyle/ph1.jpg"],
    colors: [{ name: "Obsidian", hex: "#111111" }],
    description: "A connected ride experience designed for urban commuting and comfort.",
    details: ["Smart app integration", "Long-range battery", "Foldable-ready design"],
    paymentOptions: ["Installments available"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "w1": {
    id: "w1",
    name: "Nexel Watch 2",
    subtitle: "Everyday Health",
    price: 249,
    images: ["/prd_pics/lifestyle/case1.jpg"],
    colors: [{ name: "Silver", hex: "#c9c9c9" }],
    description: "Daily health tracking with a clean, modern display and long battery life.",
    details: ["Sleep tracking", "Heart rate monitoring", "Water resistant"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "w3": {
    id: "w3",
    name: "Nexel Sound X",
    subtitle: "Wireless Audio",
    price: 229,
    images: ["/prd_pics/lifestyle/sony.jpg"],
    colors: [{ name: "Black", hex: "#000000" }],
    description: "Balanced sound and comfort for long listening sessions.",
    details: ["Bluetooth", "All-day battery", "Comfort fit"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "g1": {
    id: "g1",
    name: "Nexel Tech Case",
    subtitle: "Carry Essentials",
    price: 59,
    images: ["/prd_pics/lifestyle/case.jpg"],
    colors: [{ name: "Grey", hex: "#666666" }],
    description: "Organize your daily tech essentials with a minimal case design.",
    details: ["Water-resistant fabric", "Zipper pockets", "Compact carry"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "g2": {
    id: "g2",
    name: "Nexel Hub X",
    subtitle: "Kitchen Utility",
    price: 199,
    images: [
      "/prd_pics/minimalistic/Screenshot 2026-05-05 at 18.43.57.png",
      "/prd_pics/minimalistic/Screenshot 2026-05-05 at 18.44.00.png",
    ],
    colors: [{ name: "Cream", hex: "#f3efe6" }],
    description: "A versatile countertop tool designed for everyday prep and convenience.",
    details: ["Multiple modes", "Easy clean", "Durable build"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
  "g3": {
    id: "g3",
    name: "Nexel Box Pro",
    subtitle: "Smart Storage",
    price: 89,
    images: [
      "/prd_pics/minimalistic/Screenshot 2026-05-05 at 18.44.15.png",
    ],
    colors: [{ name: "White", hex: "#ffffff" }],
    description: "Keep accessories organized with a clean, modern storage solution.",
    details: ["Compact footprint", "Durable shell", "Minimal design"],
    paymentOptions: ["Pay in full"],
    shipping: ["Free shipping"],
    relatedProducts: [],
  },
};

export function getProduct(id: string): ProductData | null {
  return PRODUCTS[id] ?? null;
}

export function getAllProductIds(): string[] {
  return Object.keys(PRODUCTS);
}
